export const sentances = [
    "The delicious aroma from the kitchen was ruined by cigarette smoke.",
    "The manager of the fruit stand always sat and only sold vegetables.",
    "He was the type of guy who liked Christmas lights on his house in the middle of July.",
    "When nobody is around, the trees gossip about the people who have walked under them.",
    "If eating three egg omelets causes weight gain, budgie eggs are a good substitute.",
    "Excitement replaced fear until the final moment.",
    "The green tea and avocado smoothie turned out exactly as would be expected.",
    "The swirled lollipop had issues with the pop rock candy.",
    "I may struggle with geography, but I'm sure I'm somewhere around here.",
    "Check back tomorrow I will see if the book has arrived.",
    "He had a vague sense that trees gave birth to dinosaurs.",
    "Stop waiting for exceptional things to just happen",
    "As the rental car rolled to a stop on the dark road, her fear increased by the moment",
    "Imagine his surprise when he discovered that the safe was full of pudding",
    "The external scars tell only part of the story",
    "He played the game as if his life depended on it and the truth was that it did",
    "The view from the lighthouse excited even the most seasoned traveler",
    "There were a lot of paintings of monkeys waving bamboo sticks in the gallery",
    "Sometimes you have to just give up and win by cheating",
    "For oil spots on the floor, nothing beats parking a motorbike in the lounge",
    "He found the chocolate covered roaches quite tasty",
    "I've traveled all around Africa and still haven't found the gnu who stole my scarf",
    "He stepped gingerly onto the bridge knowing that enchantment awaited on the other side",
    "I am never at home on Sundays",
    "Mary realized if her calculator had a history, it would be more embarrassing than her computer browser history",
    "The most exciting eureka moment I've had was when I realized that the instructions on food packets were just guidelines",
    "The skeleton had skeletons of his own in the closet",
    "I caught my squirrel rustling through my gym bag",
    "Traveling became almost extinct during the pandemic",
    "As he entered the church he could hear the soft voice of someone whispering into a cell phone",
    "She found it strange that people use their cellphones to actually talk to one another",
    "My secretary is the only person who truly understands my stamp collecting obsession",
    "The snow covered path was no help in finding his way out of the back country",
    "If you don't like toenails, you probably shouldn't look at your feet",
    "When confronted with a rotary dial phone the teenager was perplexed",
    "She borrowed the book from him many years ago and hasn't yet returned it",
    "Her hair was windswept as she rode in the black convertible",
    "I was fishing for compliments and accidentally caught a trout",
    "My dentist tells me that chewing bricks is very bad for your teeth",
    "Nudist colonies shun fig leaf couture",
    "Lightning Paradise was the local hangout joint where the group usually ended up spending the night",
    "The door swung open to reveal pink giraffes and red elephants",
    "The child's favorite Christmas gift was the large box her father's lawnmower came in",
    "Today I dressed my unicorn in preparation for the race",
    "The family's excitement over going to Disneyland was crazier than she anticipated",
    "The newly planted trees were held up by wooden frames in hopes they could survive the next storm",
    "Poison ivy grew through the fence they said was impenetrable",
    "Writing a list of random sentences is harder than I initially thought it would be",
    "The fish listened intently to what the frogs had to say",
    "A good example of a useful vegetable is medicinal rhubarb",
    "Karen realized the only way she was getting into heaven was to cheat",
    "Today arrived with a crash of my car through the garage door",
    "Always bring cinnamon buns on a deep sea diving expedition",
    "They improved dramatically once the lead singer left",
    "The complicated school homework left the parents trying to help their kids quite confused",
    "The elderly neighborhood became enraged over the coyotes who had been blamed for the poodle's disappearance",
    "He excelled at firing people nicely",
    "I cheated while playing the darts tournament by using a longbow",
    "It would have been a better night if the guys next to us weren't in the splash zone",
    "Sometimes I stare at a door or a wall and I wonder what is this reality, why am I alive, and what is this all about",
    "Italy is my favorite country in fact, I plan to spend two weeks there next year",
  ]

  